name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install and Build
        run: |
          npm install pnpm -g
          pnpm install
          cd ./packages/demo && npm run build

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.NODE }}
          commit_message: deploy to github pages
          publish_dir: ./packages/demo/dist
